### ISSUE TITLE
tentools

### ISSUE THREAD

**Issue by Raxusd** [matthewfro1717/Dave-and-Bambi-3.0-Psych-Engine-Port#1]
### Describe your problem here.

It tells me to install tentools, where do i install tentools

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows x64

### Did you edit anything in this build? If so, mention or summarize your changes.

Nothing edited

**Comment by matthewfro1717** [comment]
Here is tentools https://github.com/TentaRJ/tentools
